a = input('digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('è um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('Esta em letra maiuscula? ', a.isupper())
print('Esta em minusculo? ', a.islower())
print("Esta capitalizada? ", a.istitle())
